use std::path::Path;

const DEFAULT_PRODUCT_NAME: &str = "local76 Suite";
const DEFAULT_COMPANY_NAME: &str = "local76";
const DEFAULT_LEGAL_COPYRIGHT: &str = "Copyright \u{00A9} 2026 local76";

fn main() {
    let ico_path = "assets/brand/app.ico";
    let pkg = std::env::var("CARGO_PKG_NAME").unwrap_or_default();

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }
    if !Path::new(ico_path).exists() {
        return;
    }

    // Migrated from winres 0.1 to embed-resource 2.x.
    // The local76 brand defaults are mirrored from
    // library::build_resources::{DEFAULT_PRODUCT_NAME, DEFAULT_COMPANY_NAME,
    // DEFAULT_LEGAL_COPYRIGHT} — the reason they're inlined here is that
    // this crate's `library` dependency is via a git source, and a
    // build-dep needs to share a single canonical source with the runtime
    // dep. New crates that pull `library` via `path =` can use the
    // `library::build_resources` API instead — see
    // library/docs/VISUAL_STANDARDS.md § C.
    // NOTE: Windows SDK 10.0.26100.0 rc.exe has a known ICONDIR-corruption
    // bug for multi-size ICOs (see library/docs/ICON_TROUBLESHOOTING.md).
    // The VERSIONINFO is correct; the ICONDIR will be fixed when the
    // toolchain is updated.
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let rc_dir = Path::new(&manifest_dir).join("build");
    let _ = std::fs::create_dir_all(&rc_dir);
    let rc_path = rc_dir.join("windows_resource.rc");
    let ico_abs = Path::new(&manifest_dir)
        .join(ico_path)
        .to_string_lossy()
        .replace('\\', "/");

    let rc = format!(
        r#"// Auto-generated by trance/build.rs
1 ICON "{ico}"

1 VERSIONINFO
FILEVERSION 1,0,0,0
PRODUCTVERSION 1,0,0,0
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904E4"
        BEGIN
            VALUE "CompanyName",     "{company}\0"
            VALUE "FileDescription", "{file_desc}\0"
            VALUE "LegalCopyright",  "{copyright}\0"
            VALUE "ProductName",     "{product}\0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1252
    END
END
"#,
        ico = ico_abs,
        company = DEFAULT_COMPANY_NAME,
        file_desc = pkg,
        copyright = DEFAULT_LEGAL_COPYRIGHT,
        product = DEFAULT_PRODUCT_NAME,
    );
    std::fs::write(&rc_path, rc).expect("failed to write windows_resource.rc");
    println!("cargo:rerun-if-changed={}", ico_path);

    embed_resource::compile(rc_path.to_string_lossy().replace('\\', "/"), embed_resource::NONE);
}
